### PR TITLE
Remove dependency on < rails 5

### PR DESCRIPTION
**Pull request by WesleyKapow**
This opens up gem for use with rails 5.0.0

Addresses #6

### CODE REVIEW

**Comment by KaoruDev** [comment]
Yay thank you for contributing! Do you know of a way to add specs for each version of Rails I'd love to have specs before bumping it up to Rails 5. Otherwise I'll try to give it a go next weekend, thanks again!

**Comment by WesleyKapow** [comment]
You mean like running the specs with rails 3 and then with rails 4 and then 5?

Hmmm https://github.com/thoughtbot/appraisal looks like exactly what you're looking for.

**Comment by KaoruDev** [comment]
Oh nice! 👍 I'll try to add this over the weekend thanks again!

**Comment by KaoruDev** [comment]
dangit I didn't have time, I'm gonna put it on my weekend list 📆

**Comment by KaoruDev** [comment]
@wes-r thanks for pointing me to `Appraisals` #8 installs it and opens the gem up to `Rails 5` gonna close this since it's a dup. 🌮

**Pull request closed without merging**
